### PR TITLE
build: split development environment into multiple environments

### PR DESCRIPTION
**Pull request by yeising**
We split our development environment into multiple isolated tool environments to avoid conflicts between dependencies.

### CODE REVIEW

**Comment by cmeesters** [comment]
Thank you.

Please provide a brief description (as edit to the initial post). And: is this a draft or ready for review?

**Comment by cmeesters** [comment]
cool. How far are we from completing this PR?

**Comment by cmeesters** [comment]
ready for review?

**Comment by yeising** [comment]
> ready for review?

Since testing now successfully builds all environments, this branch is ready for review.

**Review by cmeesters — APPROVED** [review]
seen it working as before

**Pull request merged**
